### PR TITLE
New Addon: showSeenPosts

### PR DESCRIPTION
**Pull request by imadeanaccount1**
New Addon: `showSeenPosts`
This pull request adds the following:
- [x] Posts and comments change color when "read" for more than 3.5 seconds
- [x] Seen posts are stored and remembered in the browser's local storage
- [x] A red dot appears next to the comments icon on posts that have unread comments

The following still need to be developed before merging the PR:
- [x] Add a red dot next to a reply icon on comments that have unread replies
- [x] Add reply count to these comments
- [ ] Detect when new comments are loaded and re-run addon
- [ ] Allow marking all comments as read/unread
- [ ] Allow hiding/showing of read comments (for easier filtering)
- [ ] Support larger numbers of comments with a 25+ count (to avoid doing too many API requests)
- [ ] Make it so that when the red dot next to comment counts/reply counts is hovered, it expands and shows a number inside of it
- [ ] Wasteof Light Mode Compatibility (Cringe 💀)
- [ ] Add Outlines to read posts/comments

### CODE REVIEW

**Comment by imadeanaccount1** [comment]
Added Reply Counts and Unread Reply Indicators!
image

**Comment by TheAwesome98-Real** [comment]
idea: posts have some kind of indicator that they are being "read" (for example, fading background colour/progress bar)

**Comment by imadeanaccount1** [comment]
>  fading background colour/progress bar)

That's a really good idea (I'll definitely do that!)

**Comment by imadeanaccount1** [comment]
@all-contributors please add @TheAwesome98-Real for ideas, audio

**Pull request closed without merging**
