### PR TITLE
[New] fix addon reloading

### PR DESCRIPTION
**Pull request by imadeanaccount1**
Recreates  #63, which has the new PR "different commit histories" issue.

Original Description:
This addressed https://github.com/imadeanaccount1/wasteof.plus/issues/58. I might need to adjust more things and I still need to test a lot more.

### CODE REVIEW

**Comment by imadeanaccount1** [comment]
@all-contributors please add @imadeanaccount1 for question

**Comment by imadeanaccount1** [comment]
@all-contributors please add @imadeanaccount1 for content

**Comment by imadeanaccount1** [comment]
@mybearworld @illogicalapple can you confirm that the version in [this action's artifact](https://github.com/wasteofplus/wasteof.plus/actions/runs/5827565035) works for you. If so, I am planning on merging this tomorrow (Friday). Thanks!

**Comment by mybearworld** [comment]
Yeah it works, sorry I didn't see the message. Anyways, 🥳🥳🥳

**Pull request merged**
