### PR TITLE
Update Polls to be less ugly to non-extension users

### PR DESCRIPTION
**Pull request by imadeanaccount1**
Improves the look of wasteof.plus polls to not exclude non-wasteof.plus users or damage the experience for non-extension users. At the moment, the special polls syntax looks ugly to non-wasteof.plus users and needs to be updated. 

I am currently working on reimplementing polls as a link to an external web app for non-wasteofplus users, but in the meantime, this update will improve the experience dramatically. The function and user experience for wasteof.plus users has also been greatly improved, with new features and confirmations in the creation of polls.

The new polls look like this to wasteof.plus users: 
image

To non-extension users, polls appear as:
image

### CODE REVIEW

**Comment by imadeanaccount1** [comment]
@mybearworld do you have any thoughts on this update? (i'm asking since the polls feature was originally developed by you and idk if you had any other thoughts about how we could go about this fix)

**Comment by mybearworld** [comment]
It would be good to ensure that these work well with formatting. The current way of doing it worked around that by just using a code block, but since that doesn't work every formatting option is possible.

**Comment by imadeanaccount1** [comment]
> It would be good to ensure that these work well with formatting. The current way of doing it worked around that by just using a code block, but since that doesn't work every formatting option is possible.

nvm jeffalo said he may implement a polls alternative soon so they are unnecessary :(

**Comment by mybearworld** [comment]
> nvm jeffalo said he may implement a polls alternative soon so they are unnecessary :(

Where? That sounds exciting

**Pull request closed without merging**
